### ISSUE TITLE
`#[pg_extern]` fails Types with lifetimes inside `Option<...>`

### ISSUE THREAD

**Issue by JLockerman** [pgcentralfoundation/pgrx#268]
In `0.2.0-beta-2` creating a `#[pg_extern]` function that takes an optional argument containing a lifetime fails with `use of undeclared lifetime name`.

A repro is as follows

```rust
use std::marker::PhantomData;

use serde::{Serialize, Deserialize};

use pgx::*;

pg_module_magic!();

#[derive(PostgresType, Serialize, Deserialize)]
pub struct CustomType<'s> {
    r: PhantomData<&'s ()>,
}

#[pg_extern]
fn has_error<'s>(c: Option<CustomType<'s>>) {}
```

when attempting to compile with the default `0.2.0-beta-2` pgx scaffolding + serde this results in
```
error[E0261]: use of undeclared lifetime name `'s`
  --> src/lib.rs:15:39
   |
14 | #[pg_extern]
   |             - lifetime `'s` is missing in item created through this procedural macro
15 | fn has_error<'s>(c: Option<CustomType<'s>>) {}
   |                                       ^^ undeclared lifetime
```
