### ISSUE TITLE
0.12.0-beta prerelease bug tracking

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1769]
Please file all your complaints about the beta series of releases here. In addition to breaking certain unsound patterns _on purpose_,  I am expecting considerable bugs or failures to compile extensions that _should_ compile, so if there is a compiler error, then please try to post the full error with the code that appears to produce it. If you cannot post your original code, then please post a reasonable approximation of it, including e.g. linking to a crate in a repository somewhere I can `git clone`. Fixes for these will be released about as fast as fixes get in, but for some cases it may be decided that the issue is not fixable.

## Current versions
- pgrx 0.12.0.beta-3
- rustc 1.79-stable
- relnotes: https://github.com/pgcentralfoundation/pgrx/releases/tag/v0.12.0-beta.0

## 0.12.0-beta issues fixed in 0.12.0-beta.3
- https://github.com/pgcentralfoundation/pgrx/pull/1756
- https://github.com/pgcentralfoundation/pgrx/pull/1757
- https://github.com/pgcentralfoundation/pgrx/pull/1766
- https://github.com/pgcentralfoundation/pgrx/pull/1770
- https://github.com/pgcentralfoundation/pgrx/pull/1776

## Other improvements during beta series
- https://github.com/pgcentralfoundation/pgrx/pull/1763
- https://github.com/pgcentralfoundation/pgrx/pull/1778
- https://github.com/pgcentralfoundation/pgrx/pull/1783
- https://github.com/pgcentralfoundation/pgrx/pull/1786
- https://github.com/pgcentralfoundation/pgrx/pull/1787
- https://github.com/pgcentralfoundation/pgrx/pull/1790
- https://github.com/pgcentralfoundation/pgrx/pull/1792
- https://github.com/pgcentralfoundation/pgrx/pull/1804
- https://github.com/pgcentralfoundation/pgrx/pull/1806

**Comment by the-kenny** [comment]
A `PgRelation` argument for a `pg_extern` function used to work in `0.11` but triggers a build error in `0.12.0-beta.2`:

```rust
#[pg_extern(immutable, parallel_safe)]
fn foo(relation: PgRelation) -> Option<&'static str> {
    unimplemented!()
}
```

`0.11` translated this to:

```sql
CREATE  FUNCTION "foo"(
	"relation" regclass /* pgrx::rel::PgRelation */
) RETURNS TEXT /* core::option::Option<&str> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'foo_wrapper';
```

Error in `0.12.0-beta.2`:

```
error[E0277]: the trait bound `pgrx::PgRelation: ArgAbi<'_>` is not satisfied
   --> src/utility_fns.rs:31:31
    |
30  | #[pg_extern(immutable, parallel_safe)]
    | -------------------------------------- in this procedural macro expansion
31  | fn foo(relation: PgRelation) -> Option<&'static str> {
    |        ^^^^^^^^ the trait `ArgAbi<'_>` is not implemented for `pgrx::PgRelation`
    |
    = help: the following other types implement trait `ArgAbi<'fcx>`:
              &'fcx CStr
              &'fcx [u8]
              &'fcx str
              *mut FunctionCallInfoBaseData
              AnyArray
              AnyElement
              AnyNumeric
              BOX
            and 34 others
note: required by a bound in `pgrx::callconv::Args::<'a, 'fcx>::next_arg_unchecked`
   --> .cargo/registry/src/index.crates.io-6f17d22bba15001f/pgrx-0.12.0-beta.2/src/callconv.rs:823:41
    |
823 |     pub unsafe fn next_arg_unchecked<T: ArgAbi<'fcx>>(&mut self) -> Option<T> {
    |                                         ^^^^^^^^^^^^ required by this bound in `Args::<'a, 'fcx>::next_arg_unchecked`
    = note: this error originates in the attribute macro `pg_extern` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I'm not sure if this is intentional (or expected), but it used to work in `0.11`. Workaround should be easy on my side, so feel free to mark this as 'works as intended' :-)

**Comment by workingjubilee** [comment]
Hm. I am trying to decide if it being usable as an argument is useful or correct. I opened that as #1773.

I will impl ArgAbi for it depending on the answers to that.

**Comment by workingjubilee** [comment]
> Workaround should be easy on my side, so feel free to mark this as 'works as intended' :-)

[We don't make mistakes, we have happy accidents.](https://www.youtube.com/watch?v=wCsO56kWwTc)
