### ISSUE TITLE
Fail to build pg_search extention after upgrade to pgrx 0.12.4

### ISSUE THREAD

**Issue by Traverso** [pgcentralfoundation/pgrx#1882]
After pg_search upgraded to pgrx 0.12.4 it fails to build on an M1 Mac running Sonoma 14.6.1. XCode version: 15.3.0.0.1.1708646388. I have attached the complete console output.
[pg_search_build_fail.txt](https://github.com/user-attachments/files/17150772/pg_search_build_fail.txt)

**Comment by eeeebbbbrrrr** [comment]
Based on some offline discussions with @Traverso, this appears to be the result of #1844.  /cc @usamoi 

Looks like we're generating functions from some system headers we shouldn't?  The list of actual errors in the attached .txt file are

```
 [shim for PG v15] [stderr] ./../wrap_static_fns.c:8:81: error: call to undeclared function 'OSReadSwapInt16'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  [shim for PG v15] [stderr] uint16_t OSReadSwapInt16__extern(const void *_base, uintptr_t _offset) { return OSReadSwapInt16(_base, _offset); }
  [shim for PG v15] [stderr]                                                                                 ^
 
  [shim for PG v15] [stderr] ./../wrap_static_fns.c:9:81: error: call to undeclared function 'OSReadSwapInt32'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  [shim for PG v15] [stderr] uint32_t OSReadSwapInt32__extern(const void *_base, uintptr_t _offset) { return OSReadSwapInt32(_base, _offset); }
  [shim for PG v15] [stderr]                                                                                 ^

 [shim for PG v15] [stderr] ./../wrap_static_fns.c:10:81: error: call to undeclared function 'OSReadSwapInt64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  [shim for PG v15] [stderr] uint64_t OSReadSwapInt64__extern(const void *_base, uintptr_t _offset) { return OSReadSwapInt64(_base, _offset); }
  [shim for PG v15] [stderr]                                                                                 ^

 [shim for PG v15] [stderr] ./../wrap_static_fns.c:11:81: error: call to undeclared function 'OSWriteSwapInt16'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  [shim for PG v15] [stderr] void OSWriteSwapInt16__extern(void *_base, uintptr_t _offset, uint16_t _data) { OSWriteSwapInt16(_base, _offset, _data); }
  [shim for PG v15] [stderr]                                                                                 ^
 
 [shim for PG v15] [stderr] ./../wrap_static_fns.c:12:81: error: call to undeclared function 'OSWriteSwapInt32'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  [shim for PG v15] [stderr] void OSWriteSwapInt32__extern(void *_base, uintptr_t _offset, uint32_t _data) { OSWriteSwapInt32(_base, _offset, _data); }
  [shim for PG v15] [stderr]                                                                                 ^

 [shim for PG v15] [stderr] ./../wrap_static_fns.c:13:81: error: call to undeclared function 'OSWriteSwapInt64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  [shim for PG v15] [stderr] void OSWriteSwapInt64__extern(void *_base, uintptr_t _offset, uint64_t _data) { OSWriteSwapInt64(_base, _offset, _data); }
  [shim for PG v15] [stderr]                                                                                 ^
 ```
 
 The list of symbols is:
 
 ```
OSReadSwapInt16
OSReadSwapInt32
OSReadSwapInt64
OSWriteSwapInt16
OSWriteSwapInt32
OSWriteSwapInt64
```

I'm gonna take a look and see if we can't just deny-list these.

**Comment by eeeebbbbrrrr** [comment]
~~Hi @Traverso, in the mean time, can you try adding the "libkern" header directory to your bindings path, like so:~~

Actually, nevermind.  It doesn't work.

**Comment by usamoi** [comment]
I think this should compile with #1854 merged since it applies same flags (including `-I` and `-isysroot`) to `bindgen` and `cc`. If `bindgen` finds it, `cc` should find it too.

**Comment by eeeebbbbrrrr** [comment]
@usamoi you think what should compile?

I can actually reproduce the OP's error locally on my mac.

**Comment by usamoi** [comment]
I mean `pg_search` + `pgrx 0.12.4` should not compile and `pg_search` + `develop` should compile.

**Comment by eeeebbbbrrrr** [comment]
hmm.  let me validate that since I can recreate the problem.  If so, v0.12.5, which I intend to release today, will just fix it.

**Comment by eeeebbbbrrrr** [comment]
okay, yes, `pgrx:develop` compiles just fine.  Excellent.

I do need to set this, however:

```shell
$ BINDGEN_EXTRA_CLANG_ARGS="-I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include" cargo pgrx run pg15 
```

If I don't, `cargo pgrx run` errors with:

```
  build_paths=BuildPaths { manifest_dir: "/Users/e_ridge/_work/pgrx/pgrx-pg-sys", out_dir: "/Users/e_ridge/_work/paradedb/target/debug/build/pgrx-pg-sys-2ea0b78ebbbb07cc/out", src_dir: "/Users/e_ridge/_work/pgrx/pgrx-pg-sys/src/include", shim_src: "/Users/e_ridge/_work/pgrx/pgrx-pg-sys/pgrx-cshim.c", shim_dst: "/Users/e_ridge/_work/paradedb/target/debug/build/pgrx-pg-sys-2ea0b78ebbbb07cc/out/pgrx-cshim.c" }
  Generating bindings for pg15
  pg_config --configure CLANG = None
  Bindgen found Apple clang version 16.0.0 (clang-1600.0.26.3)
  found libclang at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
  Found include dirs ["/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/16/include"]
  /Applications/Postgres.app/Contents/Versions/15/include/postgresql/server/c.h:59:10: fatal error: 'stdio.h' file not found
  Error: bindgen failed for pg15

  Caused by:
     0: Unable to generate bindings for pg15
     1: clang diagnosed error: /Applications/Postgres.app/Contents/Versions/15/include/postgresql/server/c.h:59:10: fatal error: 'stdio.h' file not found
```

But I suppose this is just how MacOS works, perhaps in conjunction with the "Postgres.app" program, which the OP is using.

**Comment by eeeebbbbrrrr** [comment]
@Traverso this will be resolved as part of pgrx v0.12.5, which I'll be releasing today.  Once that's out, I'll coordinate with the pg_search folks to do what they need to do (which includes me!).

@usamoi, thanks for the assist!  ❤️
